### PR TITLE
Finish moving to Crossdock org

### PR DESCRIPTION
**Pull request by HelloGrayson**
@abhinav @kriskowal @bombela

### CODE REVIEW

**Comment by yurishkuro** [comment]
Where will reusable things like sink, behavior funcs go?

**Comment by HelloGrayson** [comment]
@yurishkuro check out github.com/crossdock/crossdock-go

**Comment by HelloGrayson** [comment]
@yurishkuro I'm moving everything to this org so we have room to grow, i.e. add additional clients

**Comment by HelloGrayson** [comment]
(abg says ship it)

**Comment by yurishkuro** [comment]
crossdock-go is a bit confusing, e.g. it has `combinations.go`, which is not something that behavior implementation needs, and `doc.go` refers to `behavior.Sink` which I don't see. Maybe it's WIP?

**Comment by HelloGrayson** [comment]
@yurishkuro its def a WIP. Take a look at these files in yarpc-go:
- how to setup crossdock -  https://github.com/yarpc/yarpc-go/blob/master/crossdock/client/start.go
- how to integrate crossdock into regular test suite - https://github.com/yarpc/yarpc-go/blob/master/crossdock/main_test.go

You'll see that `crossdock.Combinations` is being used in the second one.

**Comment by yurishkuro** [comment]
> You'll see that crossdock.Combinations is being used in the second one.

I see, so it essentially runs the crossdock-style test against a single repo without docker. Neat. Although, it looks like it's using the same fixed ports as the real crossdock test, does it not cause issues in CI?

**Comment by HelloGrayson** [comment]
@yurishkuro hasn't been a problem yet, as we run these serially. 

This lib has a long way to go and there is a ton of things we can do to improve the experience - please create issues as you see things!

**Pull request merged**
