### PR TITLE
Rename from Xlang to Crossdock

### PR DESCRIPTION
**Pull request by kriskowal**
For consideration of the @yarpc/yarpc

### CODE REVIEW

**Comment by kriskowal** [comment]
This also renames DIMENSION to AXIS. It might be a gentler migration path to create a new repository, deprecate this one, so we don’t break existing xlang usage.

**Comment by HelloGrayson** [comment]
Before landing this, we can rename the repo so we wont break existing `yarpc/xlang` integrations.

**Comment by HelloGrayson** [comment]
Also, I'll need to update the docker creds in `.travis.yml`

**Comment by breerly** [comment]
OK - I renamed the repo. Going to merge master in now.

**Pull request merged**
