### PR TITLE
WIP - Dump TAP results and qualify tests as TAP cases

### PR DESCRIPTION
**Pull request by kriskowal**
r @breerly

### CODE REVIEW

**Comment by HelloGrayson** [comment]
I think I'm coming around to this. Let's wait until we land #11 before merging this.

**Comment by HelloGrayson** [comment]
Does TAP allow for interleaving of structured data? Let's say test clients want to return some json...

**Comment by kriskowal** [comment]
TAP ignores any text it does not recognize.

**Comment by HelloGrayson** [comment]
Cool. Wondering how we could parse structured data out of the response if we needed to...

Don't want to put us into a corner

**Comment by HelloGrayson** [comment]
Let's land the other 2 PR's, then I'll rebase this.

**Comment by HelloGrayson** [comment]
hello?

**Comment by HelloGrayson** [comment]
killing this since we'll be defining a more api-ish interaction with test harnesses

**Pull request closed without merging**
